(function(){
"use strict";
const known=value=>value===true?"Detected":value===false?"Not detected by source":"Unknown / not assessed";
const show=value=>value===undefined||value===null||value===""?"Not available":String(value);
function overview(result){
 const found=Boolean(result.operator?.name&&result.operator.name!=="Unknown"),p=result.privacy;
 return {
  operator:found?"Network operator identified: "+result.operator.name:"Network operator not identified by the available sources",
  contact:result.enquiry?"Enquiry target: "+result.enquiry.name+" · "+result.enquiry.status:result.contacts.length?"Registry contacts found. A legal-request channel still needs verification.":"Contact details unavailable in the consulted sources.",
  vpn:p.conflicts?.includes("vpn")?"VPN assessments conflict: review the source details.":p.services?.length>1?"Several intermediary providers reported: "+p.services.map(s=>s.name).join(", "):p.service?"VPN / intermediary provider reported: "+p.service:p.vpn===true?"VPN detected by source; provider name not supplied.":p.vpn===false?"VPN not detected by source.":"VPN identification not assessed: detection data unavailable."
 };
}
function missingLegalRoute(result){return (result.operator.name!=="Unknown"?"The network operator is identified as "+result.operator.name+". ":"")+"This directory does not yet list a verified legal-request channel for it. "+(result.contacts.length?"Published registry contacts are listed below to help route the enquiry. ":"")+"Confirm the responsible legal entity and its official procedure; an abuse contact is not necessarily a legal-request mailbox.";}
function enquiryLines(r){const e=r.enquiry;return e?["Provider to verify / contact: "+e.name+" · "+e.type,e.status,e.basis,...(e.subscriber_scope?[e.subscriber_scope]:[]),...(e.records_to_request?["Information to request: "+e.records_to_request]:[]),...(e.email?["Email: "+e.email]:[]),...(e.phone?["Phone: "+e.phone]:[]),...(e.address?["Published contact address: "+e.address]:[]),...(e.country?["Provider jurisdiction from policy: "+e.country]:[]),...(e.url?["Contact / procedure: "+e.url]:[]),...(e.scope?[e.scope]:[]),...(e.contact_source?["Contact source: "+e.contact_source]:[])]:[];}
function assessmentLines(p){return (p.assessments||[]).map(a=>a.source+": VPN "+known(a.vpn)+"; proxy "+known(a.proxy)+"; Tor "+known(a.tor)+"; hosting "+known(a.hosting)+". Named services: "+(a.services.map(s=>s.name).join(", ")||"Not supplied")+(a.confidence!==undefined&&a.confidence!==null?". Source confidence in positive detections: "+a.confidence+"/100":"")+(a.last_seen?". Last positive detection: "+a.last_seen:"")+(a.data_time?". Data updated: "+a.data_time:""));}
function sections(result,incident={}){
 const r=result,g=r.geolocation,p=r.privacy,o=r.operator,reg=r.registration,summary=overview(r);
 return [
  {title:"INVESTIGATION CONTEXT",lines:[summary.operator+"\n"+summary.contact+"\n"+summary.vpn,"IP: "+r.ip+" ("+r.family+")","Lookup time (UTC): "+r.queried_at,"Coverage: "+r.status,"Case reference: "+show(incident.reference),"Observed time (UTC, analyst supplied): "+show(incident.observed_at),"Source port: "+show(incident.source_port)+" · Protocol: "+show(incident.protocol)]},
  {title:"WHO TO CONTACT",lines:enquiryLines(r)},
  {title:"NETWORK / OPERATOR",lines:["Network operator: "+o.name+" · Source: "+o.source,"Routing ASN: "+show(o.asns.join(", "))+" · Prefix: "+show(o.prefix),"Network type: "+show(o.type)+" · Operator domain: "+show(o.domain),"Registry name: "+show(reg?.name)+" · Registrant: "+show(reg?.registrant),"Registered range: "+(reg?reg.start+" – "+reg.end:"Not available"),"Registration country (not geolocation or confirmed jurisdiction): "+show(reg?.country),"Registry last changed: "+show(reg?.updated_at)]},
  {title:"APPROXIMATE GEOLOCATION",lines:g?["Country / region / city: "+[g.country,g.region,g.city].filter(Boolean).join(" / "),"Coordinates: "+show(g.latitude)+", "+show(g.longitude),"Accuracy radius (km): "+show(g.radius_km)+" · Timezone: "+show(g.timezone),"Source: "+g.source+" · Source data time: "+show(g.data_time),"IP location estimate, not a person, household or street address."]:["Geolocation unavailable."]},
  {title:"VPN / INTERMEDIARIES",lines:[summary.vpn,...[["VPN","vpn"],["Proxy","proxy"],["Tor exit","tor"],["Relay","relay"],["Hosting","hosting"],["Anycast","anycast"]].map(([label,key])=>label+": "+(p.conflicts?.includes(key)?"Conflicting assessments":known(p[key]))),...assessmentLines(p),"Source: "+p.source+". The network operator and a VPN service may be different entities."]},
  {title:"PROVIDER CONTACT CHANNELS",lines:r.provider_contacts.length?r.provider_contacts.flatMap(c=>[c.name+" · "+c.kind+" · "+c.target_type,...(c.email?["Email: "+c.email]:[]),...(c.country?["Provider country: "+c.country]:[]),...(c.address?["Postal address: "+c.address]:[]),...(c.url?["Contact / policy: "+c.url]:[]),...(c.policy_url?["Procedure source: "+c.policy_url]:[]),...(c.scope?[c.scope]:[]),(c.checked_on?"Directory checked: "+c.checked_on+" · ":"")+c.basis]):[missingLegalRoute(r)]},
  {title:"REGISTRY / TECHNICAL CONTACTS",lines:r.contacts.length?r.contacts.flatMap(c=>[c.name+" · Roles: "+c.roles.join(", "),"Email: "+show(c.emails.join(", "))+" · Phone: "+show(c.phones.join(", ")),"Registry contact postal address: "+show(c.address),"Source: "+(c.source||"RIR RDAP")]):["No contact published by the consulted sources."]},
  {title:"INVESTIGATOR HANDOFF",lines:["Preserve original logs, the public IP, exact observation time and timezone, source port and protocol. Confirm the provider and receiving legal entity through your agency's procedure.",p.vpn===true?"A VPN exit is indicated. Follow the identified VPN provider's current official procedure; this tool cannot reveal the address behind it.":"Establish whether the network serves the subscriber directly or is an intermediary before routing a request.","No request has been sent. Public metadata does not establish identity or the existence of retained logs.","Analyst notes: "+show(incident.notes)]},
  {title:"COVERAGE & LIMITATIONS",lines:[...r.warnings,...r.limitations]},
  {title:"SOURCES",lines:r.sources.map(s=>s.name+" · "+s.status+(s.reason?" ("+s.reason+")":"")+" · Retrieved: "+s.retrieved_at+"\n"+s.url)}
 ];
}
function build(result,incident){return {filename:"CT-Atlas-IP-"+result.ip,eyebrow:"CT ATLAS · IP INTELLIGENCE",title:"IP investigation brief",meta:result.ip+" · "+result.queried_at,footer:"CT Atlas · Investigator orientation · Current public metadata",blocks:sections(result,incident).flatMap(s=>[{type:"heading",text:s.title},...s.lines.map(text=>({type:"body",text}))])};}
window.CTAtlasIPReport={build,sections,known,show,overview,missingLegalRoute,enquiryLines,assessmentLines};
})();
